apiVersion: v1
kind: Secret
metadata:
    name: maria-secret
    namespace: my-cloud
type: Opaque
data:
    maria-root-password: cGFzc3dvcmQ=
    maria-username: dXNlcm5hbWU=
    maria-password: cGFzc3dvcmQ=