apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-owncloud
  namespace: my-cloud
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /private
    server: 192.168.0.24
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-owncloud
  namespace: my-cloud
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi